### ISSUE TITLE
New debug logging broke scripts

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo-testing#130]
When running the `./bin/cingest` script, maven will fail to build the shaded jar.  This is due to the `accumulo version` command now logging debug information.  The conf/env.sh script gets the version from the command and after printing it to a file, I saw it was setting `accumulo.version` to this:
<pre>
2020-12-03T10:53:35,524 [classloader.AccumuloClassLoader] DEBUG: Using Accumulo configuration at /home/mike/workspace/uno/install/accumulo-2.1.0-SNAPSHOT/conf/accumulo.properties
2020-12-03T10:53:35,593 [classloader.AccumuloClassLoader] DEBUG: Create 2nd tier ClassLoader using URLs: []
2.1.0-SNAPSHOT
</pre>

**Comment by ctubbsii** [comment]
It looks like the default logging for Accumulo would send this to STDERR, so the script shouldn't pick it up. However, it seems there's a different log4j.properties file on the class path in the accumulo-testing repo, that just uses a basic console logger to send stuff to STDOUT, where this could be picked up.

One naive approach would be to change conf/env.sh to `grep -v 'DEBUG'`, but a better fix would be configure accumulo-testing to use log4j2 instead of slf4j-log4j12, and use an appropriate log4j2 config file (such as the default one that ships in Accumulo).

**Comment by milleruntime** [comment]
I did figure out my log4j config was coming from the test jar that I had placed in the lib folder of Accumulo.  I found this system property to be super helpful: `-Dlog4j.debug`

I still think it would be nice that the script won't fail if you have debug enabled.
